
from tensordict import TensorDict
from tensordict.nn import TensorDictModuleBase
from abc import ABC, abstractmethod

class Policy(TensorDictModuleBase, ABC):
    '''
    Abstract base class for policy functions.

    Takes the current state of the environment and generates 
    an action or action distribution parameters.

    *["obs"] -> ["act"]*
    '''

    def __init__(self, proto_experience: TensorDict):
        '''
        Initialize the policy with a prototype experience.

        Parameters
        ----------
        proto_experience : TensorDict
            A TensorDict with the keys:
            - "obs": The observation tensor, which defines the observation dimension.
            - "act": The action tensor, which defines the action dimension.
        '''
        super().__init__()
        self.proto_experience = proto_experience
        self.in_keys = ['obs']
        self.out_keys = ['act']

        # Extract input and output dimensions from the prototype experience
        self.in_dim = proto_experience["obs"].shape[-1]
        self.out_dim = proto_experience["act"].shape[-1]

    @abstractmethod
    def forward(self, experience: TensorDict) -> TensorDict:
        '''
        Generate action(s) or action distribution parameters based on the current state.
        
        Parameters
        ----------
        experience : TensorDict
            A TensorDict with the keys:
            - 'obs': The current state of the environment.

        Returns
        -------
        TensorDict
            A TensorDict with the new or modified keys:
            - 'act': The action or action distribution parameters generated by the policy.
        '''
        pass
